### ISSUE TITLE
what is the url path to delete a property?

### ISSUE THREAD

**Issue by JonatanHN** [tulusibrahim/simpleDB#2]
Hi.

you can delete the data of a property but not a property?
return error 404

![image](https://user-images.githubusercontent.com/36695143/175482289-fcb9e653-f5d8-45fd-bb7c-9c7c1a0f11d2.png)

**Comment by tulusibrahim** [comment]
Hi @JonatanHN .
Im still considering adding a path to delete a property because by deleting a property all the data attached to that property will also be deleted. You can make it if you want to btw

**Comment by tulusibrahim** [comment]
Hi @JonatanHN 
The path to delete property is already created. Go check the website and you can start using it now.
